AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Type: String
    Default: "MyCloud9Environment"
    Description: "Name for the Cloud9 environment"
Resources:
  MyVPC: # VPCの作成
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  MySubnet1: # サブネットの作成
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-subnet1
  
  MySubnet2: # サブネットの作成
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-subnet2
    
  MyVPCIGW: # Internet Gatewayの作成
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  
  MyVPCIGWAttach: # VPCとInternet Gatewayの関連付け
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref MyVPCIGW
      VpcId: !Ref MyVPC
  
  Cloud9RouteTable: # Cloud9用のルートテーブルの作成
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Cloud9EnvironmentRoute

  PublicRoute: # パブリックルートの設定
    Type: AWS::EC2::Route
    DependsOn: MyVPCIGW
    Properties:
      RouteTableId: !Ref Cloud9RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyVPCIGW

  Subnet1RouteAssociation: # サブネットとルートテーブルの関連付け
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet1
      RouteTableId: !Ref Cloud9RouteTable
  
  Subnet2RouteAssociation: # サブネットとルートテーブルの関連付け
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet2
      RouteTableId: !Ref Cloud9RouteTable

  MyCloud9Environment: # Cloud9環境の作成
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: !Ref EnvironmentName
      Description: "My Cloud9 Environment"
      ImageId: "amazonlinux-2023-x86_64"
      InstanceType: "t3.small"
      SubnetId: !Ref MySubnet1
      AutomaticStopTimeMinutes: 30
      OwnerArn: !Sub "arn:aws:iam::${AWS::AccountId}:user/tonkatu"
